name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install life_expectancy package
      run: |
        pip install -e .
    - name: Verify life_expectancy installation
      run: |
        pip show life_expectancy  # This will confirm that the package is installed
    - name: List project files
      run: |
        ls -R  # This will list all files, useful to verify the data file is where it should be
    - name: Test with pytest
      run: |
        pytest
    - name: Check Python version
      run: python --version

    - name: List all installed packages
      run: pip list

    - name: List all files and directories
      run: ls -R

